name: Foundry CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          foundryup

      - name: Install dependencies
        run: forge install

      - name: Build
        run: forge build

      - name: Run tests
        run: forge test --no-match-test PatternYouDontWant
