name: CI
on: [push, pull_request, workflow_dispatch]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    name: Foundry Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        
      - name: Run Tests
        run: |
          forge --version
          forge build --sizes
          forge test -vvv

      - name: Check Format
        run: forge fmt --check